[package]
name = "b2tf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.0", features = ["cargo", "derive"] }
colored = "3.0.0"
unidiff = "0.3.3"
